version: 0.2
phases:
  install:
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo "Hola :)   !"
      - echo $EKS_CLUSTER_NAME
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl get pods
  
