# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessaging.proto\"\x0e\n\x0c\x45mptyMessage\"%\n\x04Note\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2T\n\nChatServer\x12$\n\nChatStream\x12\r.EmptyMessage\x1a\x05.Note0\x01\x12 \n\x08SendNote\x12\x05.Note\x1a\r.EmptyMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTYMESSAGE']._serialized_start=19
  _globals['_EMPTYMESSAGE']._serialized_end=33
  _globals['_NOTE']._serialized_start=35
  _globals['_NOTE']._serialized_end=72
  _globals['_CHATSERVER']._serialized_start=74
  _globals['_CHATSERVER']._serialized_end=158
# @@protoc_insertion_point(module_scope)
